import os
# Matikan log oneDNN TensorFlow agar terminal bersih
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

from flask import Flask, request, jsonify
from flask_cors import CORS
import tensorflow as tf
import numpy as np
from PIL import Image
import io
import base64
from fpdf import FPDF
from datetime import datetime

app = Flask(__name__)
CORS(app) # Izinkan Frontend mengakses Backend

# --- KONFIGURASI MODEL ---
MODEL_PATH = 'VGG16_medium.h5'
CLASS_NAMES = ['Glioma Tumor', 'Meningioma Tumor', 'No Tumor', 'Pituitary Tumor']
model = None

print("🔄 Sedang memuat model AI... Mohon tunggu.")
if os.path.exists(MODEL_PATH):
    try:
        model = tf.keras.models.load_model(MODEL_PATH)
        print("✅ Model VGG16 BERHASIL dimuat!")
        print("🚀 Server siap! Silakan buka index.html")
    except Exception as e:
        print(f"❌ Gagal memuat model: {e}")
else:
    print(f"⚠️ FILE TIDAK DITEMUKAN: {MODEL_PATH}")
    print("Pastikan file .h5 ada di folder yang sama dengan api.py")

# --- PDF GENERATOR CLASS ---
class MedicalReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'NEUROSCAN AI - LAPORAN HASIL ANALISIS', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 5, 'Unit Radiologi Digital & Kecerdasan Buatan', 0, 1, 'C')
        self.line(10, 25, 200, 25)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Halaman {self.page_no()} | Generated by NeuroScan AI System', 0, 0, 'C')

def create_pdf_base64(patient_name, diagnosis, confidence, probs):
    pdf = MedicalReport()
    pdf.add_page()
    
    # 1. Info Pasien
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "DATA PASIEN", 0, 1)
    pdf.set_font("Arial", '', 11)
    
    p_name = patient_name if patient_name else "Tanpa Nama (Anonymous)"
    
    pdf.cell(50, 8, "Nama Pasien", 0, 0)
    pdf.cell(0, 8, f": {p_name}", 0, 1)
    pdf.cell(50, 8, "Tanggal Pemeriksaan", 0, 0)
    pdf.cell(0, 8, f": {datetime.now().strftime('%d %B %Y, %H:%M')}", 0, 1)
    pdf.ln(10)

    # 2. Hasil Diagnosis
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "HASIL DETEKSI AI", 0, 1)
    
    pdf.set_fill_color(240, 248, 255)
    pdf.rect(10, pdf.get_y(), 190, 25, 'F')
    
    pdf.set_xy(15, pdf.get_y() + 5)
    pdf.set_font("Arial", 'B', 16)
    
    if diagnosis == "No Tumor":
        pdf.set_text_color(0, 128, 0) # Hijau
    else:
        pdf.set_text_color(220, 53, 69) # Merah
        
    pdf.cell(0, 10, diagnosis.upper(), 0, 1)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", '', 11)
    pdf.set_xy(15, pdf.get_y())
    pdf.cell(0, 8, f"Tingkat Keyakinan (Confidence): {confidence:.2f}%", 0, 1)
    pdf.ln(15)

    # 3. Detail Probabilitas
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "DETAIL PROBABILITAS KELAS", 0, 1)
    pdf.set_font("Arial", '', 11)
    
    for cls, score in probs.items():
        bar_len = int(score / 2)
        bar_str = '|' * bar_len
        pdf.cell(50, 8, cls, 0, 0)
        pdf.cell(20, 8, f"{score:.2f}%", 0, 0)
        pdf.set_font("Courier", '', 8)
        pdf.cell(0, 8, bar_str, 0, 1)
        pdf.set_font("Arial", '', 11)

    # 4. Disclaimer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "CATATAN: Hasil ini dihasilkan oleh sistem AI (VGG16) dan WAJIB diverifikasi oleh tenaga medis profesional.")

    return base64.b64encode(pdf.output(dest='S').encode('latin-1')).decode('utf-8')

def preprocess_image(image_bytes):
    image = Image.open(io.BytesIO(image_bytes))
    image = image.convert('RGB') # Konversi ke RGB untuk mencegah error channel Alpha
    img = image.resize((150, 150))
    img_array = np.array(img)
    img_array = img_array.astype('float32') / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

# --- RUTE HALAMAN UTAMA (FIX 404 NOT FOUND) ---
@app.route('/')
def home():
    return """
    <div style="font-family: sans-serif; text-align: center; padding: 50px;">
        <h1 style="color: #0ea5e9;">🚀 NeuroScan API Berjalan!</h1>
        <p>Server Python aktif.</p>
        <p>Silakan buka file <b>index.html</b> di folder Anda untuk menggunakan aplikasi.</p>
    </div>
    """

# --- RUTE PREDIKSI ---
@app.route('/predict', methods=['POST'])
def predict():
    if not model:
        return jsonify({'error': 'Model belum dimuat. Cek terminal server.'}), 500
        
    if 'file' not in request.files:
        return jsonify({'error': 'Tidak ada file gambar yang diupload'}), 400
    
    patient_name = request.form.get('patientName', '')
    file = request.files['file']
    
    try:
        # Proses & Prediksi
        img_bytes = file.read()
        processed_img = preprocess_image(img_bytes)
        predictions = model.predict(processed_img)
        idx = np.argmax(predictions[0])
        
        confidence = float(predictions[0][idx] * 100)
        diagnosis = CLASS_NAMES[idx]
        probabilities = {name: float(prob * 100) for name, prob in zip(CLASS_NAMES, predictions[0])}
        
        # Buat PDF
        pdf_base64 = create_pdf_base64(patient_name, diagnosis, confidence, probabilities)
        
        return jsonify({
            'status': 'success',
            'diagnosis': diagnosis,
            'confidence': confidence,
            'probabilities': probabilities,
            'pdf_report': pdf_base64
        })
        
    except Exception as e:
        print(f"Error: {e}")
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    print("Mulai Server...")
    app.run(debug=True, port=5000)